### ISSUE TITLE
Paid version

### ISSUE THREAD

**Issue by enzolovesbacon** [hexene/LocalVPN#27]
Hello @hexene,

I couldn't find no other way to contact you, so I'm opening this issue. I hope it's ok.

From my quick look on this project, it seems really well written, congratulations!

I'm still testing it on my environment, but by reading the other issues, and the fact that the last commit was 2 years ago, I can imagine there are some bugs and TODOs.

I have a startup and I'm currently in need of the functionality this project provides, but it needs to be compatible with multiple devices and must not interfere with user experience. Compatibility with too older versions of Android are not so required (like 5.1 onwards is fine, maybe even 6.0+).

I would like to know if it's possible if you could offer patches and updates on this, either as a freelancing gig or some other monetizing model that you find best.

Thanks in advance!

**Comment by hexene** [comment]
Thanks for your interest, but sorry, I'm pretty busy with my $dayjob right now.

However, I understand there are other feature-complete implementations already available, for eg: https://github.com/M66B/NetGuard (GPL though).

**Comment by enzolovesbacon** [comment]
Ok, thank you very much!
