### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by Raghunandan1606** [hexene/LocalVPN#6]
the app installs but whatever internet request (lets say google search for example) wont process.
Am not sure why it is so

**Comment by hexene** [comment]
Not enough data to reproduce. If this is still an issue, please share Android version, device model and logs.

**Comment by Random-Primate** [comment]
Reopening with info requested.
- Model Number: Moto G
- Android Version: 5.1. 
```
06-02 00:02:43.586 30313-30337/xyz.hexene.localvpn D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
06-02 00:02:43.603 30313-30313/xyz.hexene.localvpn D/Atlas: Validating map...
06-02 00:02:43.724 30313-30337/xyz.hexene.localvpn I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.016_msm8226_LA.BF.1.1.1_RB1__release_AU ()
                                                                 OpenGL ES Shader Compiler Version: E031.25.03.00
                                                                 Build Date: 02/11/15 Wed
                                                                 Local Branch: 
                                                                 Remote Branch: quic/LA.BF.1.1.1_rb1.10
                                                                 Local Patches: NONE
                                                                 Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.016 + 62ca4eb + acd831d + 9f8b442 + e027a02 + cba30ba + 53c303a + a649d79 + 23e16f8 + 5e97da7 + cbd2a44 + 33d072a + 7aacf06 + 72b33e7 + 28f6f60 + b4c13d8 +  NOTHING
06-02 00:02:43.732 30313-30337/xyz.hexene.localvpn I/OpenGLRenderer: Initialized EGL, version 1.4
06-02 00:02:43.833 30313-30337/xyz.hexene.localvpn D/OpenGLRenderer: Enabling debug mode 0
06-02 00:02:49.519 30313-30727/xyz.hexene.localvpn I/UDPInput: Started
06-02 00:02:49.524 30313-30729/xyz.hexene.localvpn D/TCPInput: Started
06-02 00:02:49.527 30313-30731/xyz.hexene.localvpn I/VPNRunnable: Started
06-02 00:02:49.529 30313-30313/xyz.hexene.localvpn I/LocalVPNService: Started
06-02 00:02:49.538 30313-30730/xyz.hexene.localvpn I/TCPOutput: Started
06-02 00:02:49.540 30313-30728/xyz.hexene.localvpn I/UDPOutput: Started
06-02 00:04:00.847 30313-30328/xyz.hexene.localvpn W/art: Suspending all threads took: 7.367ms
```

**Comment by hexene** [comment]
Have you tried this pull request already? https://github.com/hexene/LocalVPN/pull/4 If it still doesn't work, could you also share the exact version (generation/model number) of your Moto G?

**Comment by Random-Primate** [comment]
No I haven't. I'll try it out and report back. Thanks for the reply, awesome project by the way.

**Comment by Random-Primate** [comment]
Tried it but couldn't get it to work. Not sure if you'd like the logs considering its a different project so feel free to ask me for those but basically it was about connection being reset by peer, bind failed because address was already in use and broken pipe. 

My device is a Motorola XT1032 API22. I think its either a first or second gen.

**Comment by ws13** [comment]
I test the solution and it seems to process the packets correctly but the device don’t have access to internet. Can be the problem the address and route configuration in the VPN?

Thanks in advance

**Comment by jaikaushik05** [comment]
this vpn service is not disconnect on button click how can i disconnect it on button click
