### ISSUE TITLE
How to write a log

### ISSUE THREAD

**Issue by aneddamattia** [hexene/LocalVPN#7]
Hi, i would know one information, after the capturing of the packets i need to write a log in .pcap file, because i need to analyse the traffic on a certain website.

Example:
Android app --> Capture traffic ---> Log .pcap --> Conversion in .har

So, my question is: using your code how i can create a log (.pcap) ?

Best Regards

**Comment by hexene** [comment]
You'll either have to convert the packet data to the pcap format yourself or use a library like jnetpcap.

**Comment by aneddamattia** [comment]
Could you explain to me how i can convert the packet data to the .pcap ?

Is it correct affirm that  i must "get" the information in:

            FileChannel vpnInput = new FileInputStream(vpnFileDescriptor).getChannel();
            FileChannel vpnOutput = new FileOutputStream(vpnFileDescriptor).getChannel();

to capture the data that i need ?
